// The Font Awesome Free 5.15.1 catalogue that ships in
// Glory2Him.WebApp/wwwroot/assets/vendor/font-awesome — the same bundle index.html loads.
//
// Generated, not hand-written. The icon names and their codepoints come from css/all.min.css
// (every `.fa-<name>:before { content: "\fxxx" }` rule); the styles come from which of the
// three shipped SVG webfonts carries that codepoint — fa-solid-900, fa-regular-400,
// fa-brands-400. An icon appears in more than one style when more than one font has the
// glyph, which is why `styles` is a list. Regenerate this file if the vendor bundle is
// upgraded; a stale entry renders as an empty box rather than an icon.
//
// This is v5, so the style class is `fas` / `far` / `fab` — the v6 `fa-solid` / `fa-regular`
// / `fa-brands` spellings are not defined by this stylesheet and render nothing.

export type FontAwesomeStyle = 'fas' | 'far' | 'fab';

export interface FontAwesomeIcon {
    name: string;
    styles: ReadonlyArray<FontAwesomeStyle>;
}

export const fontAwesomeIcons: ReadonlyArray<FontAwesomeIcon> = [
    { name: '500px', styles: ['fab'] },
    { name: 'accessible-icon', styles: ['fab'] },
    { name: 'accusoft', styles: ['fab'] },
    { name: 'acquisitions-incorporated', styles: ['fab'] },
    { name: 'ad', styles: ['fas'] },
    { name: 'address-book', styles: ['fas', 'far'] },
    { name: 'address-card', styles: ['fas', 'far'] },
    { name: 'adjust', styles: ['fas'] },
    { name: 'adn', styles: ['fab'] },
    { name: 'adversal', styles: ['fab'] },
    { name: 'affiliatetheme', styles: ['fab'] },
    { name: 'air-freshener', styles: ['fas'] },
    { name: 'airbnb', styles: ['fab'] },
    { name: 'algolia', styles: ['fab'] },
    { name: 'align-center', styles: ['fas'] },
    { name: 'align-justify', styles: ['fas'] },
    { name: 'align-left', styles: ['fas'] },
    { name: 'align-right', styles: ['fas'] },
    { name: 'alipay', styles: ['fab'] },
    { name: 'allergies', styles: ['fas'] },
    { name: 'amazon', styles: ['fab'] },
    { name: 'amazon-pay', styles: ['fab'] },
    { name: 'ambulance', styles: ['fas'] },
    { name: 'american-sign-language-interpreting', styles: ['fas'] },
    { name: 'amilia', styles: ['fab'] },
    { name: 'anchor', styles: ['fas'] },
    { name: 'android', styles: ['fab'] },
    { name: 'angellist', styles: ['fab'] },
    { name: 'angle-double-down', styles: ['fas'] },
    { name: 'angle-double-left', styles: ['fas'] },
    { name: 'angle-double-right', styles: ['fas'] },
    { name: 'angle-double-up', styles: ['fas'] },
    { name: 'angle-down', styles: ['fas'] },
    { name: 'angle-left', styles: ['fas'] },
    { name: 'angle-right', styles: ['fas'] },
    { name: 'angle-up', styles: ['fas'] },
    { name: 'angry', styles: ['fas', 'far'] },
    { name: 'angrycreative', styles: ['fab'] },
    { name: 'angular', styles: ['fab'] },
    { name: 'ankh', styles: ['fas'] },
    { name: 'app-store', styles: ['fab'] },
    { name: 'app-store-ios', styles: ['fab'] },
    { name: 'apper', styles: ['fab'] },
    { name: 'apple', styles: ['fab'] },
    { name: 'apple-alt', styles: ['fas'] },
    { name: 'apple-pay', styles: ['fab'] },
    { name: 'archive', styles: ['fas'] },
    { name: 'archway', styles: ['fas'] },
    { name: 'arrow-alt-circle-down', styles: ['fas', 'far'] },
    { name: 'arrow-alt-circle-left', styles: ['fas', 'far'] },
    { name: 'arrow-alt-circle-right', styles: ['fas', 'far'] },
    { name: 'arrow-alt-circle-up', styles: ['fas', 'far'] },
    { name: 'arrow-circle-down', styles: ['fas'] },
    { name: 'arrow-circle-left', styles: ['fas'] },
    { name: 'arrow-circle-right', styles: ['fas'] },
    { name: 'arrow-circle-up', styles: ['fas'] },
    { name: 'arrow-down', styles: ['fas'] },
    { name: 'arrow-left', styles: ['fas'] },
    { name: 'arrow-right', styles: ['fas'] },
    { name: 'arrow-up', styles: ['fas'] },
    { name: 'arrows-alt', styles: ['fas'] },
    { name: 'arrows-alt-h', styles: ['fas'] },
    { name: 'arrows-alt-v', styles: ['fas'] },
    { name: 'artstation', styles: ['fab'] },
    { name: 'assistive-listening-systems', styles: ['fas'] },
    { name: 'asterisk', styles: ['fas'] },
    { name: 'asymmetrik', styles: ['fab'] },
    { name: 'at', styles: ['fas'] },
    { name: 'atlas', styles: ['fas'] },
    { name: 'atlassian', styles: ['fab'] },
    { name: 'atom', styles: ['fas'] },
    { name: 'audible', styles: ['fab'] },
    { name: 'audio-description', styles: ['fas'] },
    { name: 'autoprefixer', styles: ['fab'] },
    { name: 'avianex', styles: ['fab'] },
    { name: 'aviato', styles: ['fab'] },
    { name: 'award', styles: ['fas'] },
    { name: 'aws', styles: ['fab'] },
    { name: 'baby', styles: ['fas'] },
    { name: 'baby-carriage', styles: ['fas'] },
    { name: 'backspace', styles: ['fas'] },
    { name: 'backward', styles: ['fas'] },
    { name: 'bacon', styles: ['fas'] },
    { name: 'bacteria', styles: ['fas'] },
    { name: 'bacterium', styles: ['fas'] },
    { name: 'bahai', styles: ['fas'] },
    { name: 'balance-scale', styles: ['fas'] },
    { name: 'balance-scale-left', styles: ['fas'] },
    { name: 'balance-scale-right', styles: ['fas'] },
    { name: 'ban', styles: ['fas'] },
    { name: 'band-aid', styles: ['fas'] },
    { name: 'bandcamp', styles: ['fab'] },
    { name: 'barcode', styles: ['fas'] },
    { name: 'bars', styles: ['fas'] },
    { name: 'baseball-ball', styles: ['fas'] },
    { name: 'basketball-ball', styles: ['fas'] },
    { name: 'bath', styles: ['fas'] },
    { name: 'battery-empty', styles: ['fas'] },
    { name: 'battery-full', styles: ['fas'] },
    { name: 'battery-half', styles: ['fas'] },
    { name: 'battery-quarter', styles: ['fas'] },
    { name: 'battery-three-quarters', styles: ['fas'] },
    { name: 'battle-net', styles: ['fab'] },
    { name: 'bed', styles: ['fas'] },
    { name: 'beer', styles: ['fas'] },
    { name: 'behance', styles: ['fab'] },
    { name: 'behance-square', styles: ['fab'] },
    { name: 'bell', styles: ['fas', 'far'] },
    { name: 'bell-slash', styles: ['fas', 'far'] },
    { name: 'bezier-curve', styles: ['fas'] },
    { name: 'bible', styles: ['fas'] },
    { name: 'bicycle', styles: ['fas'] },
    { name: 'biking', styles: ['fas'] },
    { name: 'bimobject', styles: ['fab'] },
    { name: 'binoculars', styles: ['fas'] },
    { name: 'biohazard', styles: ['fas'] },
    { name: 'birthday-cake', styles: ['fas'] },
    { name: 'bitbucket', styles: ['fab'] },
    { name: 'bitcoin', styles: ['fab'] },
    { name: 'bity', styles: ['fab'] },
    { name: 'black-tie', styles: ['fab'] },
    { name: 'blackberry', styles: ['fab'] },
    { name: 'blender', styles: ['fas'] },
    { name: 'blender-phone', styles: ['fas'] },
    { name: 'blind', styles: ['fas'] },
    { name: 'blog', styles: ['fas'] },
    { name: 'blogger', styles: ['fab'] },
    { name: 'blogger-b', styles: ['fab'] },
    { name: 'bluetooth', styles: ['fab'] },
    { name: 'bluetooth-b', styles: ['fab'] },
    { name: 'bold', styles: ['fas'] },
    { name: 'bolt', styles: ['fas'] },
    { name: 'bomb', styles: ['fas'] },
    { name: 'bone', styles: ['fas'] },
    { name: 'bong', styles: ['fas'] },
    { name: 'book', styles: ['fas'] },
    { name: 'book-dead', styles: ['fas'] },
    { name: 'book-medical', styles: ['fas'] },
    { name: 'book-open', styles: ['fas'] },
    { name: 'book-reader', styles: ['fas'] },
    { name: 'bookmark', styles: ['fas', 'far'] },
    { name: 'bootstrap', styles: ['fab'] },
    { name: 'border-all', styles: ['fas'] },
    { name: 'border-none', styles: ['fas'] },
    { name: 'border-style', styles: ['fas'] },
    { name: 'bowling-ball', styles: ['fas'] },
    { name: 'box', styles: ['fas'] },
    { name: 'box-open', styles: ['fas'] },
    { name: 'box-tissue', styles: ['fas'] },
    { name: 'boxes', styles: ['fas'] },
    { name: 'braille', styles: ['fas'] },
    { name: 'brain', styles: ['fas'] },
    { name: 'bread-slice', styles: ['fas'] },
    { name: 'briefcase', styles: ['fas'] },
    { name: 'briefcase-medical', styles: ['fas'] },
    { name: 'broadcast-tower', styles: ['fas'] },
    { name: 'broom', styles: ['fas'] },
    { name: 'brush', styles: ['fas'] },
    { name: 'btc', styles: ['fab'] },
    { name: 'buffer', styles: ['fab'] },
    { name: 'bug', styles: ['fas'] },
    { name: 'building', styles: ['fas', 'far'] },
    { name: 'bullhorn', styles: ['fas'] },
    { name: 'bullseye', styles: ['fas'] },
    { name: 'burn', styles: ['fas'] },
    { name: 'buromobelexperte', styles: ['fab'] },
    { name: 'bus', styles: ['fas'] },
    { name: 'bus-alt', styles: ['fas'] },
    { name: 'business-time', styles: ['fas'] },
    { name: 'buy-n-large', styles: ['fab'] },
    { name: 'buysellads', styles: ['fab'] },
    { name: 'calculator', styles: ['fas'] },
    { name: 'calendar', styles: ['fas', 'far'] },
    { name: 'calendar-alt', styles: ['fas', 'far'] },
    { name: 'calendar-check', styles: ['fas', 'far'] },
    { name: 'calendar-day', styles: ['fas'] },
    { name: 'calendar-minus', styles: ['fas', 'far'] },
    { name: 'calendar-plus', styles: ['fas', 'far'] },
    { name: 'calendar-times', styles: ['fas', 'far'] },
    { name: 'calendar-week', styles: ['fas'] },
    { name: 'camera', styles: ['fas'] },
    { name: 'camera-retro', styles: ['fas'] },
    { name: 'campground', styles: ['fas'] },
    { name: 'canadian-maple-leaf', styles: ['fab'] },
    { name: 'candy-cane', styles: ['fas'] },
    { name: 'cannabis', styles: ['fas'] },
    { name: 'capsules', styles: ['fas'] },
    { name: 'car', styles: ['fas'] },
    { name: 'car-alt', styles: ['fas'] },
    { name: 'car-battery', styles: ['fas'] },
    { name: 'car-crash', styles: ['fas'] },
    { name: 'car-side', styles: ['fas'] },
    { name: 'caravan', styles: ['fas'] },
    { name: 'caret-down', styles: ['fas'] },
    { name: 'caret-left', styles: ['fas'] },
    { name: 'caret-right', styles: ['fas'] },
    { name: 'caret-square-down', styles: ['fas', 'far'] },
    { name: 'caret-square-left', styles: ['fas', 'far'] },
    { name: 'caret-square-right', styles: ['fas', 'far'] },
    { name: 'caret-square-up', styles: ['fas', 'far'] },
    { name: 'caret-up', styles: ['fas'] },
    { name: 'carrot', styles: ['fas'] },
    { name: 'cart-arrow-down', styles: ['fas'] },
    { name: 'cart-plus', styles: ['fas'] },
    { name: 'cash-register', styles: ['fas'] },
    { name: 'cat', styles: ['fas'] },
    { name: 'cc-amazon-pay', styles: ['fab'] },
    { name: 'cc-amex', styles: ['fab'] },
    { name: 'cc-apple-pay', styles: ['fab'] },
    { name: 'cc-diners-club', styles: ['fab'] },
    { name: 'cc-discover', styles: ['fab'] },
    { name: 'cc-jcb', styles: ['fab'] },
    { name: 'cc-mastercard', styles: ['fab'] },
    { name: 'cc-paypal', styles: ['fab'] },
    { name: 'cc-stripe', styles: ['fab'] },
    { name: 'cc-visa', styles: ['fab'] },
    { name: 'centercode', styles: ['fab'] },
    { name: 'centos', styles: ['fab'] },
    { name: 'certificate', styles: ['fas'] },
    { name: 'chair', styles: ['fas'] },
    { name: 'chalkboard', styles: ['fas'] },
    { name: 'chalkboard-teacher', styles: ['fas'] },
    { name: 'charging-station', styles: ['fas'] },
    { name: 'chart-area', styles: ['fas'] },
    { name: 'chart-bar', styles: ['fas', 'far'] },
    { name: 'chart-line', styles: ['fas'] },
    { name: 'chart-pie', styles: ['fas'] },
    { name: 'check', styles: ['fas'] },
    { name: 'check-circle', styles: ['fas', 'far'] },
    { name: 'check-double', styles: ['fas'] },
    { name: 'check-square', styles: ['fas', 'far'] },
    { name: 'cheese', styles: ['fas'] },
    { name: 'chess', styles: ['fas'] },
    { name: 'chess-bishop', styles: ['fas'] },
    { name: 'chess-board', styles: ['fas'] },
    { name: 'chess-king', styles: ['fas'] },
    { name: 'chess-knight', styles: ['fas'] },
    { name: 'chess-pawn', styles: ['fas'] },
    { name: 'chess-queen', styles: ['fas'] },
    { name: 'chess-rook', styles: ['fas'] },
    { name: 'chevron-circle-down', styles: ['fas'] },
    { name: 'chevron-circle-left', styles: ['fas'] },
    { name: 'chevron-circle-right', styles: ['fas'] },
    { name: 'chevron-circle-up', styles: ['fas'] },
    { name: 'chevron-down', styles: ['fas'] },
    { name: 'chevron-left', styles: ['fas'] },
    { name: 'chevron-right', styles: ['fas'] },
    { name: 'chevron-up', styles: ['fas'] },
    { name: 'child', styles: ['fas'] },
    { name: 'chrome', styles: ['fab'] },
    { name: 'chromecast', styles: ['fab'] },
    { name: 'church', styles: ['fas'] },
    { name: 'circle', styles: ['fas', 'far'] },
    { name: 'circle-notch', styles: ['fas'] },
    { name: 'city', styles: ['fas'] },
    { name: 'clinic-medical', styles: ['fas'] },
    { name: 'clipboard', styles: ['fas', 'far'] },
    { name: 'clipboard-check', styles: ['fas'] },
    { name: 'clipboard-list', styles: ['fas'] },
    { name: 'clock', styles: ['fas', 'far'] },
    { name: 'clone', styles: ['fas', 'far'] },
    { name: 'closed-captioning', styles: ['fas', 'far'] },
    { name: 'cloud', styles: ['fas'] },
    { name: 'cloud-download-alt', styles: ['fas'] },
    { name: 'cloud-meatball', styles: ['fas'] },
    { name: 'cloud-moon', styles: ['fas'] },
    { name: 'cloud-moon-rain', styles: ['fas'] },
    { name: 'cloud-rain', styles: ['fas'] },
    { name: 'cloud-showers-heavy', styles: ['fas'] },
    { name: 'cloud-sun', styles: ['fas'] },
    { name: 'cloud-sun-rain', styles: ['fas'] },
    { name: 'cloud-upload-alt', styles: ['fas'] },
    { name: 'cloudflare', styles: ['fab'] },
    { name: 'cloudscale', styles: ['fab'] },
    { name: 'cloudsmith', styles: ['fab'] },
    { name: 'cloudversify', styles: ['fab'] },
    { name: 'cocktail', styles: ['fas'] },
    { name: 'code', styles: ['fas'] },
    { name: 'code-branch', styles: ['fas'] },
    { name: 'codepen', styles: ['fab'] },
    { name: 'codiepie', styles: ['fab'] },
    { name: 'coffee', styles: ['fas'] },
    { name: 'cog', styles: ['fas'] },
    { name: 'cogs', styles: ['fas'] },
    { name: 'coins', styles: ['fas'] },
    { name: 'columns', styles: ['fas'] },
    { name: 'comment', styles: ['fas', 'far'] },
    { name: 'comment-alt', styles: ['fas', 'far'] },
    { name: 'comment-dollar', styles: ['fas'] },
    { name: 'comment-dots', styles: ['fas', 'far'] },
    { name: 'comment-medical', styles: ['fas'] },
    { name: 'comment-slash', styles: ['fas'] },
    { name: 'comments', styles: ['fas', 'far'] },
    { name: 'comments-dollar', styles: ['fas'] },
    { name: 'compact-disc', styles: ['fas'] },
    { name: 'compass', styles: ['fas', 'far'] },
    { name: 'compress', styles: ['fas'] },
    { name: 'compress-alt', styles: ['fas'] },
    { name: 'compress-arrows-alt', styles: ['fas'] },
    { name: 'concierge-bell', styles: ['fas'] },
    { name: 'confluence', styles: ['fab'] },
    { name: 'connectdevelop', styles: ['fab'] },
    { name: 'contao', styles: ['fab'] },
    { name: 'cookie', styles: ['fas'] },
    { name: 'cookie-bite', styles: ['fas'] },
    { name: 'copy', styles: ['fas', 'far'] },
    { name: 'copyright', styles: ['fas', 'far'] },
    { name: 'cotton-bureau', styles: ['fab'] },
    { name: 'couch', styles: ['fas'] },
    { name: 'cpanel', styles: ['fab'] },
    { name: 'creative-commons', styles: ['fab'] },
    { name: 'creative-commons-by', styles: ['fab'] },
    { name: 'creative-commons-nc', styles: ['fab'] },
    { name: 'creative-commons-nc-eu', styles: ['fab'] },
    { name: 'creative-commons-nc-jp', styles: ['fab'] },
    { name: 'creative-commons-nd', styles: ['fab'] },
    { name: 'creative-commons-pd', styles: ['fab'] },
    { name: 'creative-commons-pd-alt', styles: ['fab'] },
    { name: 'creative-commons-remix', styles: ['fab'] },
    { name: 'creative-commons-sa', styles: ['fab'] },
    { name: 'creative-commons-sampling', styles: ['fab'] },
    { name: 'creative-commons-sampling-plus', styles: ['fab'] },
    { name: 'creative-commons-share', styles: ['fab'] },
    { name: 'creative-commons-zero', styles: ['fab'] },
    { name: 'credit-card', styles: ['fas', 'far'] },
    { name: 'critical-role', styles: ['fab'] },
    { name: 'crop', styles: ['fas'] },
    { name: 'crop-alt', styles: ['fas'] },
    { name: 'cross', styles: ['fas'] },
    { name: 'crosshairs', styles: ['fas'] },
    { name: 'crow', styles: ['fas'] },
    { name: 'crown', styles: ['fas'] },
    { name: 'crutch', styles: ['fas'] },
    { name: 'css3', styles: ['fab'] },
    { name: 'css3-alt', styles: ['fab'] },
    { name: 'cube', styles: ['fas'] },
    { name: 'cubes', styles: ['fas'] },
    { name: 'cut', styles: ['fas'] },
    { name: 'cuttlefish', styles: ['fab'] },
    { name: 'd-and-d', styles: ['fab'] },
    { name: 'd-and-d-beyond', styles: ['fab'] },
    { name: 'dailymotion', styles: ['fab'] },
    { name: 'dashcube', styles: ['fab'] },
    { name: 'database', styles: ['fas'] },
    { name: 'deaf', styles: ['fas'] },
    { name: 'deezer', styles: ['fab'] },
    { name: 'delicious', styles: ['fab'] },
    { name: 'democrat', styles: ['fas'] },
    { name: 'deploydog', styles: ['fab'] },
    { name: 'deskpro', styles: ['fab'] },
    { name: 'desktop', styles: ['fas'] },
    { name: 'dev', styles: ['fab'] },
    { name: 'deviantart', styles: ['fab'] },
    { name: 'dharmachakra', styles: ['fas'] },
    { name: 'dhl', styles: ['fab'] },
    { name: 'diagnoses', styles: ['fas'] },
    { name: 'diaspora', styles: ['fab'] },
    { name: 'dice', styles: ['fas'] },
    { name: 'dice-d20', styles: ['fas'] },
    { name: 'dice-d6', styles: ['fas'] },
    { name: 'dice-five', styles: ['fas'] },
    { name: 'dice-four', styles: ['fas'] },
    { name: 'dice-one', styles: ['fas'] },
    { name: 'dice-six', styles: ['fas'] },
    { name: 'dice-three', styles: ['fas'] },
    { name: 'dice-two', styles: ['fas'] },
    { name: 'digg', styles: ['fab'] },
    { name: 'digital-ocean', styles: ['fab'] },
    { name: 'digital-tachograph', styles: ['fas'] },
    { name: 'directions', styles: ['fas'] },
    { name: 'discord', styles: ['fab'] },
    { name: 'discourse', styles: ['fab'] },
    { name: 'disease', styles: ['fas'] },
    { name: 'divide', styles: ['fas'] },
    { name: 'dizzy', styles: ['fas', 'far'] },
    { name: 'dna', styles: ['fas'] },
    { name: 'dochub', styles: ['fab'] },
    { name: 'docker', styles: ['fab'] },
    { name: 'dog', styles: ['fas'] },
    { name: 'dollar-sign', styles: ['fas'] },
    { name: 'dolly', styles: ['fas'] },
    { name: 'dolly-flatbed', styles: ['fas'] },
    { name: 'donate', styles: ['fas'] },
    { name: 'door-closed', styles: ['fas'] },
    { name: 'door-open', styles: ['fas'] },
    { name: 'dot-circle', styles: ['fas', 'far'] },
    { name: 'dove', styles: ['fas'] },
    { name: 'download', styles: ['fas'] },
    { name: 'draft2digital', styles: ['fab'] },
    { name: 'drafting-compass', styles: ['fas'] },
    { name: 'dragon', styles: ['fas'] },
    { name: 'draw-polygon', styles: ['fas'] },
    { name: 'dribbble', styles: ['fab'] },
    { name: 'dribbble-square', styles: ['fab'] },
    { name: 'dropbox', styles: ['fab'] },
    { name: 'drum', styles: ['fas'] },
    { name: 'drum-steelpan', styles: ['fas'] },
    { name: 'drumstick-bite', styles: ['fas'] },
    { name: 'drupal', styles: ['fab'] },
    { name: 'dumbbell', styles: ['fas'] },
    { name: 'dumpster', styles: ['fas'] },
    { name: 'dumpster-fire', styles: ['fas'] },
    { name: 'dungeon', styles: ['fas'] },
    { name: 'dyalog', styles: ['fab'] },
    { name: 'earlybirds', styles: ['fab'] },
    { name: 'ebay', styles: ['fab'] },
    { name: 'edge', styles: ['fab'] },
    { name: 'edge-legacy', styles: ['fab'] },
    { name: 'edit', styles: ['fas', 'far'] },
    { name: 'egg', styles: ['fas'] },
    { name: 'eject', styles: ['fas'] },
    { name: 'elementor', styles: ['fab'] },
    { name: 'ellipsis-h', styles: ['fas'] },
    { name: 'ellipsis-v', styles: ['fas'] },
    { name: 'ello', styles: ['fab'] },
    { name: 'ember', styles: ['fab'] },
    { name: 'empire', styles: ['fab'] },
    { name: 'envelope', styles: ['fas', 'far'] },
    { name: 'envelope-open', styles: ['fas', 'far'] },
    { name: 'envelope-open-text', styles: ['fas'] },
    { name: 'envelope-square', styles: ['fas'] },
    { name: 'envira', styles: ['fab'] },
    { name: 'equals', styles: ['fas'] },
    { name: 'eraser', styles: ['fas'] },
    { name: 'erlang', styles: ['fab'] },
    { name: 'ethereum', styles: ['fab'] },
    { name: 'ethernet', styles: ['fas'] },
    { name: 'etsy', styles: ['fab'] },
    { name: 'euro-sign', styles: ['fas'] },
    { name: 'evernote', styles: ['fab'] },
    { name: 'exchange-alt', styles: ['fas'] },
    { name: 'exclamation', styles: ['fas'] },
    { name: 'exclamation-circle', styles: ['fas'] },
    { name: 'exclamation-triangle', styles: ['fas'] },
    { name: 'expand', styles: ['fas'] },
    { name: 'expand-alt', styles: ['fas'] },
    { name: 'expand-arrows-alt', styles: ['fas'] },
    { name: 'expeditedssl', styles: ['fab'] },
    { name: 'external-link-alt', styles: ['fas'] },
    { name: 'external-link-square-alt', styles: ['fas'] },
    { name: 'eye', styles: ['fas', 'far'] },
    { name: 'eye-dropper', styles: ['fas'] },
    { name: 'eye-slash', styles: ['fas', 'far'] },
    { name: 'facebook', styles: ['fab'] },
    { name: 'facebook-f', styles: ['fab'] },
    { name: 'facebook-messenger', styles: ['fab'] },
    { name: 'facebook-square', styles: ['fab'] },
    { name: 'fan', styles: ['fas'] },
    { name: 'fantasy-flight-games', styles: ['fab'] },
    { name: 'fast-backward', styles: ['fas'] },
    { name: 'fast-forward', styles: ['fas'] },
    { name: 'faucet', styles: ['fas'] },
    { name: 'fax', styles: ['fas'] },
    { name: 'feather', styles: ['fas'] },
    { name: 'feather-alt', styles: ['fas'] },
    { name: 'fedex', styles: ['fab'] },
    { name: 'fedora', styles: ['fab'] },
    { name: 'female', styles: ['fas'] },
    { name: 'fighter-jet', styles: ['fas'] },
    { name: 'figma', styles: ['fab'] },
    { name: 'file', styles: ['fas', 'far'] },
    { name: 'file-alt', styles: ['fas', 'far'] },
    { name: 'file-archive', styles: ['fas', 'far'] },
    { name: 'file-audio', styles: ['fas', 'far'] },
    { name: 'file-code', styles: ['fas', 'far'] },
    { name: 'file-contract', styles: ['fas'] },
    { name: 'file-csv', styles: ['fas'] },
    { name: 'file-download', styles: ['fas'] },
    { name: 'file-excel', styles: ['fas', 'far'] },
    { name: 'file-export', styles: ['fas'] },
    { name: 'file-image', styles: ['fas', 'far'] },
    { name: 'file-import', styles: ['fas'] },
    { name: 'file-invoice', styles: ['fas'] },
    { name: 'file-invoice-dollar', styles: ['fas'] },
    { name: 'file-medical', styles: ['fas'] },
    { name: 'file-medical-alt', styles: ['fas'] },
    { name: 'file-pdf', styles: ['fas', 'far'] },
    { name: 'file-powerpoint', styles: ['fas', 'far'] },
    { name: 'file-prescription', styles: ['fas'] },
    { name: 'file-signature', styles: ['fas'] },
    { name: 'file-upload', styles: ['fas'] },
    { name: 'file-video', styles: ['fas', 'far'] },
    { name: 'file-word', styles: ['fas', 'far'] },
    { name: 'fill', styles: ['fas'] },
    { name: 'fill-drip', styles: ['fas'] },
    { name: 'film', styles: ['fas'] },
    { name: 'filter', styles: ['fas'] },
    { name: 'fingerprint', styles: ['fas'] },
    { name: 'fire', styles: ['fas'] },
    { name: 'fire-alt', styles: ['fas'] },
    { name: 'fire-extinguisher', styles: ['fas'] },
    { name: 'firefox', styles: ['fab'] },
    { name: 'firefox-browser', styles: ['fab'] },
    { name: 'first-aid', styles: ['fas'] },
    { name: 'first-order', styles: ['fab'] },
    { name: 'first-order-alt', styles: ['fab'] },
    { name: 'firstdraft', styles: ['fab'] },
    { name: 'fish', styles: ['fas'] },
    { name: 'fist-raised', styles: ['fas'] },
    { name: 'flag', styles: ['fas', 'far'] },
    { name: 'flag-checkered', styles: ['fas'] },
    { name: 'flag-usa', styles: ['fas'] },
    { name: 'flask', styles: ['fas'] },
    { name: 'flickr', styles: ['fab'] },
    { name: 'flipboard', styles: ['fab'] },
    { name: 'flushed', styles: ['fas', 'far'] },
    { name: 'fly', styles: ['fab'] },
    { name: 'folder', styles: ['fas', 'far'] },
    { name: 'folder-minus', styles: ['fas'] },
    { name: 'folder-open', styles: ['fas', 'far'] },
    { name: 'folder-plus', styles: ['fas'] },
    { name: 'font', styles: ['fas'] },
    { name: 'font-awesome', styles: ['fab'] },
    { name: 'font-awesome-alt', styles: ['fab'] },
    { name: 'font-awesome-flag', styles: ['fab'] },
    { name: 'fonticons', styles: ['fab'] },
    { name: 'fonticons-fi', styles: ['fab'] },
    { name: 'football-ball', styles: ['fas'] },
    { name: 'fort-awesome', styles: ['fab'] },
    { name: 'fort-awesome-alt', styles: ['fab'] },
    { name: 'forumbee', styles: ['fab'] },
    { name: 'forward', styles: ['fas'] },
    { name: 'foursquare', styles: ['fab'] },
    { name: 'free-code-camp', styles: ['fab'] },
    { name: 'freebsd', styles: ['fab'] },
    { name: 'frog', styles: ['fas'] },
    { name: 'frown', styles: ['fas', 'far'] },
    { name: 'frown-open', styles: ['fas', 'far'] },
    { name: 'fulcrum', styles: ['fab'] },
    { name: 'funnel-dollar', styles: ['fas'] },
    { name: 'futbol', styles: ['fas', 'far'] },
    { name: 'galactic-republic', styles: ['fab'] },
    { name: 'galactic-senate', styles: ['fab'] },
    { name: 'gamepad', styles: ['fas'] },
    { name: 'gas-pump', styles: ['fas'] },
    { name: 'gavel', styles: ['fas'] },
    { name: 'gem', styles: ['fas', 'far'] },
    { name: 'genderless', styles: ['fas'] },
    { name: 'get-pocket', styles: ['fab'] },
    { name: 'gg', styles: ['fab'] },
    { name: 'gg-circle', styles: ['fab'] },
    { name: 'ghost', styles: ['fas'] },
    { name: 'gift', styles: ['fas'] },
    { name: 'gifts', styles: ['fas'] },
    { name: 'git', styles: ['fab'] },
    { name: 'git-alt', styles: ['fab'] },
    { name: 'git-square', styles: ['fab'] },
    { name: 'github', styles: ['fab'] },
    { name: 'github-alt', styles: ['fab'] },
    { name: 'github-square', styles: ['fab'] },
    { name: 'gitkraken', styles: ['fab'] },
    { name: 'gitlab', styles: ['fab'] },
    { name: 'gitter', styles: ['fab'] },
    { name: 'glass-cheers', styles: ['fas'] },
    { name: 'glass-martini', styles: ['fas'] },
    { name: 'glass-martini-alt', styles: ['fas'] },
    { name: 'glass-whiskey', styles: ['fas'] },
    { name: 'glasses', styles: ['fas'] },
    { name: 'glide', styles: ['fab'] },
    { name: 'glide-g', styles: ['fab'] },
    { name: 'globe', styles: ['fas'] },
    { name: 'globe-africa', styles: ['fas'] },
    { name: 'globe-americas', styles: ['fas'] },
    { name: 'globe-asia', styles: ['fas'] },
    { name: 'globe-europe', styles: ['fas'] },
    { name: 'gofore', styles: ['fab'] },
    { name: 'golf-ball', styles: ['fas'] },
    { name: 'goodreads', styles: ['fab'] },
    { name: 'goodreads-g', styles: ['fab'] },
    { name: 'google', styles: ['fab'] },
    { name: 'google-drive', styles: ['fab'] },
    { name: 'google-pay', styles: ['fab'] },
    { name: 'google-play', styles: ['fab'] },
    { name: 'google-plus', styles: ['fab'] },
    { name: 'google-plus-g', styles: ['fab'] },
    { name: 'google-plus-square', styles: ['fab'] },
    { name: 'google-wallet', styles: ['fab'] },
    { name: 'gopuram', styles: ['fas'] },
    { name: 'graduation-cap', styles: ['fas'] },
    { name: 'gratipay', styles: ['fab'] },
    { name: 'grav', styles: ['fab'] },
    { name: 'greater-than', styles: ['fas'] },
    { name: 'greater-than-equal', styles: ['fas'] },
    { name: 'grimace', styles: ['fas', 'far'] },
    { name: 'grin', styles: ['fas', 'far'] },
    { name: 'grin-alt', styles: ['fas', 'far'] },
    { name: 'grin-beam', styles: ['fas', 'far'] },
    { name: 'grin-beam-sweat', styles: ['fas', 'far'] },
    { name: 'grin-hearts', styles: ['fas', 'far'] },
    { name: 'grin-squint', styles: ['fas', 'far'] },
    { name: 'grin-squint-tears', styles: ['fas', 'far'] },
    { name: 'grin-stars', styles: ['fas', 'far'] },
    { name: 'grin-tears', styles: ['fas', 'far'] },
    { name: 'grin-tongue', styles: ['fas', 'far'] },
    { name: 'grin-tongue-squint', styles: ['fas', 'far'] },
    { name: 'grin-tongue-wink', styles: ['fas', 'far'] },
    { name: 'grin-wink', styles: ['fas', 'far'] },
    { name: 'grip-horizontal', styles: ['fas'] },
    { name: 'grip-lines', styles: ['fas'] },
    { name: 'grip-lines-vertical', styles: ['fas'] },
    { name: 'grip-vertical', styles: ['fas'] },
    { name: 'gripfire', styles: ['fab'] },
    { name: 'grunt', styles: ['fab'] },
    { name: 'guilded', styles: ['fab'] },
    { name: 'guitar', styles: ['fas'] },
    { name: 'gulp', styles: ['fab'] },
    { name: 'h-square', styles: ['fas'] },
    { name: 'hacker-news', styles: ['fab'] },
    { name: 'hacker-news-square', styles: ['fab'] },
    { name: 'hackerrank', styles: ['fab'] },
    { name: 'hamburger', styles: ['fas'] },
    { name: 'hammer', styles: ['fas'] },
    { name: 'hamsa', styles: ['fas'] },
    { name: 'hand-holding', styles: ['fas'] },
    { name: 'hand-holding-heart', styles: ['fas'] },
    { name: 'hand-holding-medical', styles: ['fas'] },
    { name: 'hand-holding-usd', styles: ['fas'] },
    { name: 'hand-holding-water', styles: ['fas'] },
    { name: 'hand-lizard', styles: ['fas', 'far'] },
    { name: 'hand-middle-finger', styles: ['fas'] },
    { name: 'hand-paper', styles: ['fas', 'far'] },
    { name: 'hand-peace', styles: ['fas', 'far'] },
    { name: 'hand-point-down', styles: ['fas', 'far'] },
    { name: 'hand-point-left', styles: ['fas', 'far'] },
    { name: 'hand-point-right', styles: ['fas', 'far'] },
    { name: 'hand-point-up', styles: ['fas', 'far'] },
    { name: 'hand-pointer', styles: ['fas', 'far'] },
    { name: 'hand-rock', styles: ['fas', 'far'] },
    { name: 'hand-scissors', styles: ['fas', 'far'] },
    { name: 'hand-sparkles', styles: ['fas'] },
    { name: 'hand-spock', styles: ['fas', 'far'] },
    { name: 'hands', styles: ['fas'] },
    { name: 'hands-helping', styles: ['fas'] },
    { name: 'hands-wash', styles: ['fas'] },
    { name: 'handshake', styles: ['fas', 'far'] },
    { name: 'handshake-alt-slash', styles: ['fas'] },
    { name: 'handshake-slash', styles: ['fas'] },
    { name: 'hanukiah', styles: ['fas'] },
    { name: 'hard-hat', styles: ['fas'] },
    { name: 'hashtag', styles: ['fas'] },
    { name: 'hat-cowboy', styles: ['fas'] },
    { name: 'hat-cowboy-side', styles: ['fas'] },
    { name: 'hat-wizard', styles: ['fas'] },
    { name: 'hdd', styles: ['fas', 'far'] },
    { name: 'head-side-cough', styles: ['fas'] },
    { name: 'head-side-cough-slash', styles: ['fas'] },
    { name: 'head-side-mask', styles: ['fas'] },
    { name: 'head-side-virus', styles: ['fas'] },
    { name: 'heading', styles: ['fas'] },
    { name: 'headphones', styles: ['fas'] },
    { name: 'headphones-alt', styles: ['fas'] },
    { name: 'headset', styles: ['fas'] },
    { name: 'heart', styles: ['fas', 'far'] },
    { name: 'heart-broken', styles: ['fas'] },
    { name: 'heartbeat', styles: ['fas'] },
    { name: 'helicopter', styles: ['fas'] },
    { name: 'highlighter', styles: ['fas'] },
    { name: 'hiking', styles: ['fas'] },
    { name: 'hippo', styles: ['fas'] },
    { name: 'hips', styles: ['fab'] },
    { name: 'hire-a-helper', styles: ['fab'] },
    { name: 'history', styles: ['fas'] },
    { name: 'hive', styles: ['fab'] },
    { name: 'hockey-puck', styles: ['fas'] },
    { name: 'holly-berry', styles: ['fas'] },
    { name: 'home', styles: ['fas'] },
    { name: 'hooli', styles: ['fab'] },
    { name: 'hornbill', styles: ['fab'] },
    { name: 'horse', styles: ['fas'] },
    { name: 'horse-head', styles: ['fas'] },
    { name: 'hospital', styles: ['fas', 'far'] },
    { name: 'hospital-alt', styles: ['fas'] },
    { name: 'hospital-symbol', styles: ['fas'] },
    { name: 'hospital-user', styles: ['fas'] },
    { name: 'hot-tub', styles: ['fas'] },
    { name: 'hotdog', styles: ['fas'] },
    { name: 'hotel', styles: ['fas'] },
    { name: 'hotjar', styles: ['fab'] },
    { name: 'hourglass', styles: ['fas', 'far'] },
    { name: 'hourglass-end', styles: ['fas'] },
    { name: 'hourglass-half', styles: ['fas'] },
    { name: 'hourglass-start', styles: ['fas'] },
    { name: 'house-damage', styles: ['fas'] },
    { name: 'house-user', styles: ['fas'] },
    { name: 'houzz', styles: ['fab'] },
    { name: 'hryvnia', styles: ['fas'] },
    { name: 'html5', styles: ['fab'] },
    { name: 'hubspot', styles: ['fab'] },
    { name: 'i-cursor', styles: ['fas'] },
    { name: 'ice-cream', styles: ['fas'] },
    { name: 'icicles', styles: ['fas'] },
    { name: 'icons', styles: ['fas'] },
    { name: 'id-badge', styles: ['fas', 'far'] },
    { name: 'id-card', styles: ['fas', 'far'] },
    { name: 'id-card-alt', styles: ['fas'] },
    { name: 'ideal', styles: ['fab'] },
    { name: 'igloo', styles: ['fas'] },
    { name: 'image', styles: ['fas', 'far'] },
    { name: 'images', styles: ['fas', 'far'] },
    { name: 'imdb', styles: ['fab'] },
    { name: 'inbox', styles: ['fas'] },
    { name: 'indent', styles: ['fas'] },
    { name: 'industry', styles: ['fas'] },
    { name: 'infinity', styles: ['fas'] },
    { name: 'info', styles: ['fas'] },
    { name: 'info-circle', styles: ['fas'] },
    { name: 'innosoft', styles: ['fab'] },
    { name: 'instagram', styles: ['fab'] },
    { name: 'instagram-square', styles: ['fab'] },
    { name: 'instalod', styles: ['fab'] },
    { name: 'intercom', styles: ['fab'] },
    { name: 'internet-explorer', styles: ['fab'] },
    { name: 'invision', styles: ['fab'] },
    { name: 'ioxhost', styles: ['fab'] },
    { name: 'italic', styles: ['fas'] },
    { name: 'itch-io', styles: ['fab'] },
    { name: 'itunes', styles: ['fab'] },
    { name: 'itunes-note', styles: ['fab'] },
    { name: 'java', styles: ['fab'] },
    { name: 'jedi', styles: ['fas'] },
    { name: 'jedi-order', styles: ['fab'] },
    { name: 'jenkins', styles: ['fab'] },
    { name: 'jira', styles: ['fab'] },
    { name: 'joget', styles: ['fab'] },
    { name: 'joint', styles: ['fas'] },
    { name: 'joomla', styles: ['fab'] },
    { name: 'journal-whills', styles: ['fas'] },
    { name: 'js', styles: ['fab'] },
    { name: 'js-square', styles: ['fab'] },
    { name: 'jsfiddle', styles: ['fab'] },
    { name: 'kaaba', styles: ['fas'] },
    { name: 'kaggle', styles: ['fab'] },
    { name: 'key', styles: ['fas'] },
    { name: 'keybase', styles: ['fab'] },
    { name: 'keyboard', styles: ['fas', 'far'] },
    { name: 'keycdn', styles: ['fab'] },
    { name: 'khanda', styles: ['fas'] },
    { name: 'kickstarter', styles: ['fab'] },
    { name: 'kickstarter-k', styles: ['fab'] },
    { name: 'kiss', styles: ['fas', 'far'] },
    { name: 'kiss-beam', styles: ['fas', 'far'] },
    { name: 'kiss-wink-heart', styles: ['fas', 'far'] },
    { name: 'kiwi-bird', styles: ['fas'] },
    { name: 'korvue', styles: ['fab'] },
    { name: 'landmark', styles: ['fas'] },
    { name: 'language', styles: ['fas'] },
    { name: 'laptop', styles: ['fas'] },
    { name: 'laptop-code', styles: ['fas'] },
    { name: 'laptop-house', styles: ['fas'] },
    { name: 'laptop-medical', styles: ['fas'] },
    { name: 'laravel', styles: ['fab'] },
    { name: 'lastfm', styles: ['fab'] },
    { name: 'lastfm-square', styles: ['fab'] },
    { name: 'laugh', styles: ['fas', 'far'] },
    { name: 'laugh-beam', styles: ['fas', 'far'] },
    { name: 'laugh-squint', styles: ['fas', 'far'] },
    { name: 'laugh-wink', styles: ['fas', 'far'] },
    { name: 'layer-group', styles: ['fas'] },
    { name: 'leaf', styles: ['fas'] },
    { name: 'leanpub', styles: ['fab'] },
    { name: 'lemon', styles: ['fas', 'far'] },
    { name: 'less', styles: ['fab'] },
    { name: 'less-than', styles: ['fas'] },
    { name: 'less-than-equal', styles: ['fas'] },
    { name: 'level-down-alt', styles: ['fas'] },
    { name: 'level-up-alt', styles: ['fas'] },
    { name: 'life-ring', styles: ['fas', 'far'] },
    { name: 'lightbulb', styles: ['fas', 'far'] },
    { name: 'line', styles: ['fab'] },
    { name: 'link', styles: ['fas'] },
    { name: 'linkedin', styles: ['fab'] },
    { name: 'linkedin-in', styles: ['fab'] },
    { name: 'linode', styles: ['fab'] },
    { name: 'linux', styles: ['fab'] },
    { name: 'lira-sign', styles: ['fas'] },
    { name: 'list', styles: ['fas'] },
    { name: 'list-alt', styles: ['fas', 'far'] },
    { name: 'list-ol', styles: ['fas'] },
    { name: 'list-ul', styles: ['fas'] },
    { name: 'location-arrow', styles: ['fas'] },
    { name: 'lock', styles: ['fas'] },
    { name: 'lock-open', styles: ['fas'] },
    { name: 'long-arrow-alt-down', styles: ['fas'] },
    { name: 'long-arrow-alt-left', styles: ['fas'] },
    { name: 'long-arrow-alt-right', styles: ['fas'] },
    { name: 'long-arrow-alt-up', styles: ['fas'] },
    { name: 'low-vision', styles: ['fas'] },
    { name: 'luggage-cart', styles: ['fas'] },
    { name: 'lungs', styles: ['fas'] },
    { name: 'lungs-virus', styles: ['fas'] },
    { name: 'lyft', styles: ['fab'] },
    { name: 'magento', styles: ['fab'] },
    { name: 'magic', styles: ['fas'] },
    { name: 'magnet', styles: ['fas'] },
    { name: 'mail-bulk', styles: ['fas'] },
    { name: 'mailchimp', styles: ['fab'] },
    { name: 'male', styles: ['fas'] },
    { name: 'mandalorian', styles: ['fab'] },
    { name: 'map', styles: ['fas', 'far'] },
    { name: 'map-marked', styles: ['fas'] },
    { name: 'map-marked-alt', styles: ['fas'] },
    { name: 'map-marker', styles: ['fas'] },
    { name: 'map-marker-alt', styles: ['fas'] },
    { name: 'map-pin', styles: ['fas'] },
    { name: 'map-signs', styles: ['fas'] },
    { name: 'markdown', styles: ['fab'] },
    { name: 'marker', styles: ['fas'] },
    { name: 'mars', styles: ['fas'] },
    { name: 'mars-double', styles: ['fas'] },
    { name: 'mars-stroke', styles: ['fas'] },
    { name: 'mars-stroke-h', styles: ['fas'] },
    { name: 'mars-stroke-v', styles: ['fas'] },
    { name: 'mask', styles: ['fas'] },
    { name: 'mastodon', styles: ['fab'] },
    { name: 'maxcdn', styles: ['fab'] },
    { name: 'mdb', styles: ['fab'] },
    { name: 'medal', styles: ['fas'] },
    { name: 'medapps', styles: ['fab'] },
    { name: 'medium', styles: ['fab'] },
    { name: 'medium-m', styles: ['fab'] },
    { name: 'medkit', styles: ['fas'] },
    { name: 'medrt', styles: ['fab'] },
    { name: 'meetup', styles: ['fab'] },
    { name: 'megaport', styles: ['fab'] },
    { name: 'meh', styles: ['fas', 'far'] },
    { name: 'meh-blank', styles: ['fas', 'far'] },
    { name: 'meh-rolling-eyes', styles: ['fas', 'far'] },
    { name: 'memory', styles: ['fas'] },
    { name: 'mendeley', styles: ['fab'] },
    { name: 'menorah', styles: ['fas'] },
    { name: 'mercury', styles: ['fas'] },
    { name: 'meteor', styles: ['fas'] },
    { name: 'microblog', styles: ['fab'] },
    { name: 'microchip', styles: ['fas'] },
    { name: 'microphone', styles: ['fas'] },
    { name: 'microphone-alt', styles: ['fas'] },
    { name: 'microphone-alt-slash', styles: ['fas'] },
    { name: 'microphone-slash', styles: ['fas'] },
    { name: 'microscope', styles: ['fas'] },
    { name: 'microsoft', styles: ['fab'] },
    { name: 'minus', styles: ['fas'] },
    { name: 'minus-circle', styles: ['fas'] },
    { name: 'minus-square', styles: ['fas', 'far'] },
    { name: 'mitten', styles: ['fas'] },
    { name: 'mix', styles: ['fab'] },
    { name: 'mixcloud', styles: ['fab'] },
    { name: 'mixer', styles: ['fab'] },
    { name: 'mizuni', styles: ['fab'] },
    { name: 'mobile', styles: ['fas'] },
    { name: 'mobile-alt', styles: ['fas'] },
    { name: 'modx', styles: ['fab'] },
    { name: 'monero', styles: ['fab'] },
    { name: 'money-bill', styles: ['fas'] },
    { name: 'money-bill-alt', styles: ['fas', 'far'] },
    { name: 'money-bill-wave', styles: ['fas'] },
    { name: 'money-bill-wave-alt', styles: ['fas'] },
    { name: 'money-check', styles: ['fas'] },
    { name: 'money-check-alt', styles: ['fas'] },
    { name: 'monument', styles: ['fas'] },
    { name: 'moon', styles: ['fas', 'far'] },
    { name: 'mortar-pestle', styles: ['fas'] },
    { name: 'mosque', styles: ['fas'] },
    { name: 'motorcycle', styles: ['fas'] },
    { name: 'mountain', styles: ['fas'] },
    { name: 'mouse', styles: ['fas'] },
    { name: 'mouse-pointer', styles: ['fas'] },
    { name: 'mug-hot', styles: ['fas'] },
    { name: 'music', styles: ['fas'] },
    { name: 'napster', styles: ['fab'] },
    { name: 'neos', styles: ['fab'] },
    { name: 'network-wired', styles: ['fas'] },
    { name: 'neuter', styles: ['fas'] },
    { name: 'newspaper', styles: ['fas', 'far'] },
    { name: 'nimblr', styles: ['fab'] },
    { name: 'node', styles: ['fab'] },
    { name: 'node-js', styles: ['fab'] },
    { name: 'not-equal', styles: ['fas'] },
    { name: 'notes-medical', styles: ['fas'] },
    { name: 'npm', styles: ['fab'] },
    { name: 'ns8', styles: ['fab'] },
    { name: 'nutritionix', styles: ['fab'] },
    { name: 'object-group', styles: ['fas', 'far'] },
    { name: 'object-ungroup', styles: ['fas', 'far'] },
    { name: 'octopus-deploy', styles: ['fab'] },
    { name: 'odnoklassniki', styles: ['fab'] },
    { name: 'odnoklassniki-square', styles: ['fab'] },
    { name: 'oil-can', styles: ['fas'] },
    { name: 'old-republic', styles: ['fab'] },
    { name: 'om', styles: ['fas'] },
    { name: 'opencart', styles: ['fab'] },
    { name: 'openid', styles: ['fab'] },
    { name: 'opera', styles: ['fab'] },
    { name: 'optin-monster', styles: ['fab'] },
    { name: 'orcid', styles: ['fab'] },
    { name: 'osi', styles: ['fab'] },
    { name: 'otter', styles: ['fas'] },
    { name: 'outdent', styles: ['fas'] },
    { name: 'page4', styles: ['fab'] },
    { name: 'pagelines', styles: ['fab'] },
    { name: 'pager', styles: ['fas'] },
    { name: 'paint-brush', styles: ['fas'] },
    { name: 'paint-roller', styles: ['fas'] },
    { name: 'palette', styles: ['fas'] },
    { name: 'palfed', styles: ['fab'] },
    { name: 'pallet', styles: ['fas'] },
    { name: 'paper-plane', styles: ['fas', 'far'] },
    { name: 'paperclip', styles: ['fas'] },
    { name: 'parachute-box', styles: ['fas'] },
    { name: 'paragraph', styles: ['fas'] },
    { name: 'parking', styles: ['fas'] },
    { name: 'passport', styles: ['fas'] },
    { name: 'pastafarianism', styles: ['fas'] },
    { name: 'paste', styles: ['fas'] },
    { name: 'patreon', styles: ['fab'] },
    { name: 'pause', styles: ['fas'] },
    { name: 'pause-circle', styles: ['fas', 'far'] },
    { name: 'paw', styles: ['fas'] },
    { name: 'paypal', styles: ['fab'] },
    { name: 'peace', styles: ['fas'] },
    { name: 'pen', styles: ['fas'] },
    { name: 'pen-alt', styles: ['fas'] },
    { name: 'pen-fancy', styles: ['fas'] },
    { name: 'pen-nib', styles: ['fas'] },
    { name: 'pen-square', styles: ['fas'] },
    { name: 'pencil-alt', styles: ['fas'] },
    { name: 'pencil-ruler', styles: ['fas'] },
    { name: 'penny-arcade', styles: ['fab'] },
    { name: 'people-arrows', styles: ['fas'] },
    { name: 'people-carry', styles: ['fas'] },
    { name: 'pepper-hot', styles: ['fas'] },
    { name: 'perbyte', styles: ['fab'] },
    { name: 'percent', styles: ['fas'] },
    { name: 'percentage', styles: ['fas'] },
    { name: 'periscope', styles: ['fab'] },
    { name: 'person-booth', styles: ['fas'] },
    { name: 'phabricator', styles: ['fab'] },
    { name: 'phoenix-framework', styles: ['fab'] },
    { name: 'phoenix-squadron', styles: ['fab'] },
    { name: 'phone', styles: ['fas'] },
    { name: 'phone-alt', styles: ['fas'] },
    { name: 'phone-slash', styles: ['fas'] },
    { name: 'phone-square', styles: ['fas'] },
    { name: 'phone-square-alt', styles: ['fas'] },
    { name: 'phone-volume', styles: ['fas'] },
    { name: 'photo-video', styles: ['fas'] },
    { name: 'php', styles: ['fab'] },
    { name: 'pied-piper', styles: ['fab'] },
    { name: 'pied-piper-alt', styles: ['fab'] },
    { name: 'pied-piper-hat', styles: ['fab'] },
    { name: 'pied-piper-pp', styles: ['fab'] },
    { name: 'pied-piper-square', styles: ['fab'] },
    { name: 'piggy-bank', styles: ['fas'] },
    { name: 'pills', styles: ['fas'] },
    { name: 'pinterest', styles: ['fab'] },
    { name: 'pinterest-p', styles: ['fab'] },
    { name: 'pinterest-square', styles: ['fab'] },
    { name: 'pizza-slice', styles: ['fas'] },
    { name: 'place-of-worship', styles: ['fas'] },
    { name: 'plane', styles: ['fas'] },
    { name: 'plane-arrival', styles: ['fas'] },
    { name: 'plane-departure', styles: ['fas'] },
    { name: 'plane-slash', styles: ['fas'] },
    { name: 'play', styles: ['fas'] },
    { name: 'play-circle', styles: ['fas', 'far'] },
    { name: 'playstation', styles: ['fab'] },
    { name: 'plug', styles: ['fas'] },
    { name: 'plus', styles: ['fas'] },
    { name: 'plus-circle', styles: ['fas'] },
    { name: 'plus-square', styles: ['fas', 'far'] },
    { name: 'podcast', styles: ['fas'] },
    { name: 'poll', styles: ['fas'] },
    { name: 'poll-h', styles: ['fas'] },
    { name: 'poo', styles: ['fas'] },
    { name: 'poo-storm', styles: ['fas'] },
    { name: 'poop', styles: ['fas'] },
    { name: 'portrait', styles: ['fas'] },
    { name: 'pound-sign', styles: ['fas'] },
    { name: 'power-off', styles: ['fas'] },
    { name: 'pray', styles: ['fas'] },
    { name: 'praying-hands', styles: ['fas'] },
    { name: 'prescription', styles: ['fas'] },
    { name: 'prescription-bottle', styles: ['fas'] },
    { name: 'prescription-bottle-alt', styles: ['fas'] },
    { name: 'print', styles: ['fas'] },
    { name: 'procedures', styles: ['fas'] },
    { name: 'product-hunt', styles: ['fab'] },
    { name: 'project-diagram', styles: ['fas'] },
    { name: 'pump-medical', styles: ['fas'] },
    { name: 'pump-soap', styles: ['fas'] },
    { name: 'pushed', styles: ['fab'] },
    { name: 'puzzle-piece', styles: ['fas'] },
    { name: 'python', styles: ['fab'] },
    { name: 'qq', styles: ['fab'] },
    { name: 'qrcode', styles: ['fas'] },
    { name: 'question', styles: ['fas'] },
    { name: 'question-circle', styles: ['fas', 'far'] },
    { name: 'quidditch', styles: ['fas'] },
    { name: 'quinscape', styles: ['fab'] },
    { name: 'quora', styles: ['fab'] },
    { name: 'quote-left', styles: ['fas'] },
    { name: 'quote-right', styles: ['fas'] },
    { name: 'quran', styles: ['fas'] },
    { name: 'r-project', styles: ['fab'] },
    { name: 'radiation', styles: ['fas'] },
    { name: 'radiation-alt', styles: ['fas'] },
    { name: 'rainbow', styles: ['fas'] },
    { name: 'random', styles: ['fas'] },
    { name: 'raspberry-pi', styles: ['fab'] },
    { name: 'ravelry', styles: ['fab'] },
    { name: 'react', styles: ['fab'] },
    { name: 'reacteurope', styles: ['fab'] },
    { name: 'readme', styles: ['fab'] },
    { name: 'rebel', styles: ['fab'] },
    { name: 'receipt', styles: ['fas'] },
    { name: 'record-vinyl', styles: ['fas'] },
    { name: 'recycle', styles: ['fas'] },
    { name: 'red-river', styles: ['fab'] },
    { name: 'reddit', styles: ['fab'] },
    { name: 'reddit-alien', styles: ['fab'] },
    { name: 'reddit-square', styles: ['fab'] },
    { name: 'redhat', styles: ['fab'] },
    { name: 'redo', styles: ['fas'] },
    { name: 'redo-alt', styles: ['fas'] },
    { name: 'registered', styles: ['fas', 'far'] },
    { name: 'remove-format', styles: ['fas'] },
    { name: 'renren', styles: ['fab'] },
    { name: 'reply', styles: ['fas'] },
    { name: 'reply-all', styles: ['fas'] },
    { name: 'replyd', styles: ['fab'] },
    { name: 'republican', styles: ['fas'] },
    { name: 'researchgate', styles: ['fab'] },
    { name: 'resolving', styles: ['fab'] },
    { name: 'restroom', styles: ['fas'] },
    { name: 'retweet', styles: ['fas'] },
    { name: 'rev', styles: ['fab'] },
    { name: 'ribbon', styles: ['fas'] },
    { name: 'ring', styles: ['fas'] },
    { name: 'road', styles: ['fas'] },
    { name: 'robot', styles: ['fas'] },
    { name: 'rocket', styles: ['fas'] },
    { name: 'rocketchat', styles: ['fab'] },
    { name: 'rockrms', styles: ['fab'] },
    { name: 'route', styles: ['fas'] },
    { name: 'rss', styles: ['fas'] },
    { name: 'rss-square', styles: ['fas'] },
    { name: 'ruble-sign', styles: ['fas'] },
    { name: 'ruler', styles: ['fas'] },
    { name: 'ruler-combined', styles: ['fas'] },
    { name: 'ruler-horizontal', styles: ['fas'] },
    { name: 'ruler-vertical', styles: ['fas'] },
    { name: 'running', styles: ['fas'] },
    { name: 'rupee-sign', styles: ['fas'] },
    { name: 'rust', styles: ['fab'] },
    { name: 'sad-cry', styles: ['fas', 'far'] },
    { name: 'sad-tear', styles: ['fas', 'far'] },
    { name: 'safari', styles: ['fab'] },
    { name: 'salesforce', styles: ['fab'] },
    { name: 'sass', styles: ['fab'] },
    { name: 'satellite', styles: ['fas'] },
    { name: 'satellite-dish', styles: ['fas'] },
    { name: 'save', styles: ['fas', 'far'] },
    { name: 'schlix', styles: ['fab'] },
    { name: 'school', styles: ['fas'] },
    { name: 'screwdriver', styles: ['fas'] },
    { name: 'scribd', styles: ['fab'] },
    { name: 'scroll', styles: ['fas'] },
    { name: 'sd-card', styles: ['fas'] },
    { name: 'search', styles: ['fas'] },
    { name: 'search-dollar', styles: ['fas'] },
    { name: 'search-location', styles: ['fas'] },
    { name: 'search-minus', styles: ['fas'] },
    { name: 'search-plus', styles: ['fas'] },
    { name: 'searchengin', styles: ['fab'] },
    { name: 'seedling', styles: ['fas'] },
    { name: 'sellcast', styles: ['fab'] },
    { name: 'sellsy', styles: ['fab'] },
    { name: 'server', styles: ['fas'] },
    { name: 'servicestack', styles: ['fab'] },
    { name: 'shapes', styles: ['fas'] },
    { name: 'share', styles: ['fas'] },
    { name: 'share-alt', styles: ['fas'] },
    { name: 'share-alt-square', styles: ['fas'] },
    { name: 'share-square', styles: ['fas', 'far'] },
    { name: 'shekel-sign', styles: ['fas'] },
    { name: 'shield-alt', styles: ['fas'] },
    { name: 'shield-virus', styles: ['fas'] },
    { name: 'ship', styles: ['fas'] },
    { name: 'shipping-fast', styles: ['fas'] },
    { name: 'shirtsinbulk', styles: ['fab'] },
    { name: 'shoe-prints', styles: ['fas'] },
    { name: 'shopify', styles: ['fab'] },
    { name: 'shopping-bag', styles: ['fas'] },
    { name: 'shopping-basket', styles: ['fas'] },
    { name: 'shopping-cart', styles: ['fas'] },
    { name: 'shopware', styles: ['fab'] },
    { name: 'shower', styles: ['fas'] },
    { name: 'shuttle-van', styles: ['fas'] },
    { name: 'sign', styles: ['fas'] },
    { name: 'sign-in-alt', styles: ['fas'] },
    { name: 'sign-language', styles: ['fas'] },
    { name: 'sign-out-alt', styles: ['fas'] },
    { name: 'signal', styles: ['fas'] },
    { name: 'signature', styles: ['fas'] },
    { name: 'sim-card', styles: ['fas'] },
    { name: 'simplybuilt', styles: ['fab'] },
    { name: 'sink', styles: ['fas'] },
    { name: 'sistrix', styles: ['fab'] },
    { name: 'sitemap', styles: ['fas'] },
    { name: 'sith', styles: ['fab'] },
    { name: 'skating', styles: ['fas'] },
    { name: 'sketch', styles: ['fab'] },
    { name: 'skiing', styles: ['fas'] },
    { name: 'skiing-nordic', styles: ['fas'] },
    { name: 'skull', styles: ['fas'] },
    { name: 'skull-crossbones', styles: ['fas'] },
    { name: 'skyatlas', styles: ['fab'] },
    { name: 'skype', styles: ['fab'] },
    { name: 'slack', styles: ['fab'] },
    { name: 'slack-hash', styles: ['fab'] },
    { name: 'slash', styles: ['fas'] },
    { name: 'sleigh', styles: ['fas'] },
    { name: 'sliders-h', styles: ['fas'] },
    { name: 'slideshare', styles: ['fab'] },
    { name: 'smile', styles: ['fas', 'far'] },
    { name: 'smile-beam', styles: ['fas', 'far'] },
    { name: 'smile-wink', styles: ['fas', 'far'] },
    { name: 'smog', styles: ['fas'] },
    { name: 'smoking', styles: ['fas'] },
    { name: 'smoking-ban', styles: ['fas'] },
    { name: 'sms', styles: ['fas'] },
    { name: 'snapchat', styles: ['fab'] },
    { name: 'snapchat-ghost', styles: ['fab'] },
    { name: 'snapchat-square', styles: ['fab'] },
    { name: 'snowboarding', styles: ['fas'] },
    { name: 'snowflake', styles: ['fas', 'far'] },
    { name: 'snowman', styles: ['fas'] },
    { name: 'snowplow', styles: ['fas'] },
    { name: 'soap', styles: ['fas'] },
    { name: 'socks', styles: ['fas'] },
    { name: 'solar-panel', styles: ['fas'] },
    { name: 'sort', styles: ['fas'] },
    { name: 'sort-alpha-down', styles: ['fas'] },
    { name: 'sort-alpha-down-alt', styles: ['fas'] },
    { name: 'sort-alpha-up', styles: ['fas'] },
    { name: 'sort-alpha-up-alt', styles: ['fas'] },
    { name: 'sort-amount-down', styles: ['fas'] },
    { name: 'sort-amount-down-alt', styles: ['fas'] },
    { name: 'sort-amount-up', styles: ['fas'] },
    { name: 'sort-amount-up-alt', styles: ['fas'] },
    { name: 'sort-down', styles: ['fas'] },
    { name: 'sort-numeric-down', styles: ['fas'] },
    { name: 'sort-numeric-down-alt', styles: ['fas'] },
    { name: 'sort-numeric-up', styles: ['fas'] },
    { name: 'sort-numeric-up-alt', styles: ['fas'] },
    { name: 'sort-up', styles: ['fas'] },
    { name: 'soundcloud', styles: ['fab'] },
    { name: 'sourcetree', styles: ['fab'] },
    { name: 'spa', styles: ['fas'] },
    { name: 'space-shuttle', styles: ['fas'] },
    { name: 'speakap', styles: ['fab'] },
    { name: 'speaker-deck', styles: ['fab'] },
    { name: 'spell-check', styles: ['fas'] },
    { name: 'spider', styles: ['fas'] },
    { name: 'spinner', styles: ['fas'] },
    { name: 'splotch', styles: ['fas'] },
    { name: 'spotify', styles: ['fab'] },
    { name: 'spray-can', styles: ['fas'] },
    { name: 'square', styles: ['fas', 'far'] },
    { name: 'square-full', styles: ['fas'] },
    { name: 'square-root-alt', styles: ['fas'] },
    { name: 'squarespace', styles: ['fab'] },
    { name: 'stack-exchange', styles: ['fab'] },
    { name: 'stack-overflow', styles: ['fab'] },
    { name: 'stackpath', styles: ['fab'] },
    { name: 'stamp', styles: ['fas'] },
    { name: 'star', styles: ['fas', 'far'] },
    { name: 'star-and-crescent', styles: ['fas'] },
    { name: 'star-half', styles: ['fas', 'far'] },
    { name: 'star-half-alt', styles: ['fas'] },
    { name: 'star-of-david', styles: ['fas'] },
    { name: 'star-of-life', styles: ['fas'] },
    { name: 'staylinked', styles: ['fab'] },
    { name: 'steam', styles: ['fab'] },
    { name: 'steam-square', styles: ['fab'] },
    { name: 'steam-symbol', styles: ['fab'] },
    { name: 'step-backward', styles: ['fas'] },
    { name: 'step-forward', styles: ['fas'] },
    { name: 'stethoscope', styles: ['fas'] },
    { name: 'sticker-mule', styles: ['fab'] },
    { name: 'sticky-note', styles: ['fas', 'far'] },
    { name: 'stop', styles: ['fas'] },
    { name: 'stop-circle', styles: ['fas', 'far'] },
    { name: 'stopwatch', styles: ['fas'] },
    { name: 'stopwatch-20', styles: ['fas'] },
    { name: 'store', styles: ['fas'] },
    { name: 'store-alt', styles: ['fas'] },
    { name: 'store-alt-slash', styles: ['fas'] },
    { name: 'store-slash', styles: ['fas'] },
    { name: 'strava', styles: ['fab'] },
    { name: 'stream', styles: ['fas'] },
    { name: 'street-view', styles: ['fas'] },
    { name: 'strikethrough', styles: ['fas'] },
    { name: 'stripe', styles: ['fab'] },
    { name: 'stripe-s', styles: ['fab'] },
    { name: 'stroopwafel', styles: ['fas'] },
    { name: 'studiovinari', styles: ['fab'] },
    { name: 'stumbleupon', styles: ['fab'] },
    { name: 'stumbleupon-circle', styles: ['fab'] },
    { name: 'subscript', styles: ['fas'] },
    { name: 'subway', styles: ['fas'] },
    { name: 'suitcase', styles: ['fas'] },
    { name: 'suitcase-rolling', styles: ['fas'] },
    { name: 'sun', styles: ['fas', 'far'] },
    { name: 'superpowers', styles: ['fab'] },
    { name: 'superscript', styles: ['fas'] },
    { name: 'supple', styles: ['fab'] },
    { name: 'surprise', styles: ['fas', 'far'] },
    { name: 'suse', styles: ['fab'] },
    { name: 'swatchbook', styles: ['fas'] },
    { name: 'swift', styles: ['fab'] },
    { name: 'swimmer', styles: ['fas'] },
    { name: 'swimming-pool', styles: ['fas'] },
    { name: 'symfony', styles: ['fab'] },
    { name: 'synagogue', styles: ['fas'] },
    { name: 'sync', styles: ['fas'] },
    { name: 'sync-alt', styles: ['fas'] },
    { name: 'syringe', styles: ['fas'] },
    { name: 'table', styles: ['fas'] },
    { name: 'table-tennis', styles: ['fas'] },
    { name: 'tablet', styles: ['fas'] },
    { name: 'tablet-alt', styles: ['fas'] },
    { name: 'tablets', styles: ['fas'] },
    { name: 'tachometer-alt', styles: ['fas'] },
    { name: 'tag', styles: ['fas'] },
    { name: 'tags', styles: ['fas'] },
    { name: 'tape', styles: ['fas'] },
    { name: 'tasks', styles: ['fas'] },
    { name: 'taxi', styles: ['fas'] },
    { name: 'teamspeak', styles: ['fab'] },
    { name: 'teeth', styles: ['fas'] },
    { name: 'teeth-open', styles: ['fas'] },
    { name: 'telegram', styles: ['fab'] },
    { name: 'telegram-plane', styles: ['fab'] },
    { name: 'temperature-high', styles: ['fas'] },
    { name: 'temperature-low', styles: ['fas'] },
    { name: 'tencent-weibo', styles: ['fab'] },
    { name: 'tenge', styles: ['fas'] },
    { name: 'terminal', styles: ['fas'] },
    { name: 'text-height', styles: ['fas'] },
    { name: 'text-width', styles: ['fas'] },
    { name: 'th', styles: ['fas'] },
    { name: 'th-large', styles: ['fas'] },
    { name: 'th-list', styles: ['fas'] },
    { name: 'the-red-yeti', styles: ['fab'] },
    { name: 'theater-masks', styles: ['fas'] },
    { name: 'themeco', styles: ['fab'] },
    { name: 'themeisle', styles: ['fab'] },
    { name: 'thermometer', styles: ['fas'] },
    { name: 'thermometer-empty', styles: ['fas'] },
    { name: 'thermometer-full', styles: ['fas'] },
    { name: 'thermometer-half', styles: ['fas'] },
    { name: 'thermometer-quarter', styles: ['fas'] },
    { name: 'thermometer-three-quarters', styles: ['fas'] },
    { name: 'think-peaks', styles: ['fab'] },
    { name: 'thumbs-down', styles: ['fas', 'far'] },
    { name: 'thumbs-up', styles: ['fas', 'far'] },
    { name: 'thumbtack', styles: ['fas'] },
    { name: 'ticket-alt', styles: ['fas'] },
    { name: 'tiktok', styles: ['fab'] },
    { name: 'times', styles: ['fas'] },
    { name: 'times-circle', styles: ['fas', 'far'] },
    { name: 'tint', styles: ['fas'] },
    { name: 'tint-slash', styles: ['fas'] },
    { name: 'tired', styles: ['fas', 'far'] },
    { name: 'toggle-off', styles: ['fas'] },
    { name: 'toggle-on', styles: ['fas'] },
    { name: 'toilet', styles: ['fas'] },
    { name: 'toilet-paper', styles: ['fas'] },
    { name: 'toilet-paper-slash', styles: ['fas'] },
    { name: 'toolbox', styles: ['fas'] },
    { name: 'tools', styles: ['fas'] },
    { name: 'tooth', styles: ['fas'] },
    { name: 'torah', styles: ['fas'] },
    { name: 'torii-gate', styles: ['fas'] },
    { name: 'tractor', styles: ['fas'] },
    { name: 'trade-federation', styles: ['fab'] },
    { name: 'trademark', styles: ['fas'] },
    { name: 'traffic-light', styles: ['fas'] },
    { name: 'trailer', styles: ['fas'] },
    { name: 'train', styles: ['fas'] },
    { name: 'tram', styles: ['fas'] },
    { name: 'transgender', styles: ['fas'] },
    { name: 'transgender-alt', styles: ['fas'] },
    { name: 'trash', styles: ['fas'] },
    { name: 'trash-alt', styles: ['fas', 'far'] },
    { name: 'trash-restore', styles: ['fas'] },
    { name: 'trash-restore-alt', styles: ['fas'] },
    { name: 'tree', styles: ['fas'] },
    { name: 'trello', styles: ['fab'] },
    { name: 'tripadvisor', styles: ['fab'] },
    { name: 'trophy', styles: ['fas'] },
    { name: 'truck', styles: ['fas'] },
    { name: 'truck-loading', styles: ['fas'] },
    { name: 'truck-monster', styles: ['fas'] },
    { name: 'truck-moving', styles: ['fas'] },
    { name: 'truck-pickup', styles: ['fas'] },
    { name: 'tshirt', styles: ['fas'] },
    { name: 'tty', styles: ['fas'] },
    { name: 'tumblr', styles: ['fab'] },
    { name: 'tumblr-square', styles: ['fab'] },
    { name: 'tv', styles: ['fas'] },
    { name: 'twitch', styles: ['fab'] },
    { name: 'twitter', styles: ['fab'] },
    { name: 'twitter-square', styles: ['fab'] },
    { name: 'typo3', styles: ['fab'] },
    { name: 'uber', styles: ['fab'] },
    { name: 'ubuntu', styles: ['fab'] },
    { name: 'uikit', styles: ['fab'] },
    { name: 'umbraco', styles: ['fab'] },
    { name: 'umbrella', styles: ['fas'] },
    { name: 'umbrella-beach', styles: ['fas'] },
    { name: 'uncharted', styles: ['fab'] },
    { name: 'underline', styles: ['fas'] },
    { name: 'undo', styles: ['fas'] },
    { name: 'undo-alt', styles: ['fas'] },
    { name: 'uniregistry', styles: ['fab'] },
    { name: 'unity', styles: ['fab'] },
    { name: 'universal-access', styles: ['fas'] },
    { name: 'university', styles: ['fas'] },
    { name: 'unlink', styles: ['fas'] },
    { name: 'unlock', styles: ['fas'] },
    { name: 'unlock-alt', styles: ['fas'] },
    { name: 'unsplash', styles: ['fab'] },
    { name: 'untappd', styles: ['fab'] },
    { name: 'upload', styles: ['fas'] },
    { name: 'ups', styles: ['fab'] },
    { name: 'usb', styles: ['fab'] },
    { name: 'user', styles: ['fas', 'far'] },
    { name: 'user-alt', styles: ['fas'] },
    { name: 'user-alt-slash', styles: ['fas'] },
    { name: 'user-astronaut', styles: ['fas'] },
    { name: 'user-check', styles: ['fas'] },
    { name: 'user-circle', styles: ['fas', 'far'] },
    { name: 'user-clock', styles: ['fas'] },
    { name: 'user-cog', styles: ['fas'] },
    { name: 'user-edit', styles: ['fas'] },
    { name: 'user-friends', styles: ['fas'] },
    { name: 'user-graduate', styles: ['fas'] },
    { name: 'user-injured', styles: ['fas'] },
    { name: 'user-lock', styles: ['fas'] },
    { name: 'user-md', styles: ['fas'] },
    { name: 'user-minus', styles: ['fas'] },
    { name: 'user-ninja', styles: ['fas'] },
    { name: 'user-nurse', styles: ['fas'] },
    { name: 'user-plus', styles: ['fas'] },
    { name: 'user-secret', styles: ['fas'] },
    { name: 'user-shield', styles: ['fas'] },
    { name: 'user-slash', styles: ['fas'] },
    { name: 'user-tag', styles: ['fas'] },
    { name: 'user-tie', styles: ['fas'] },
    { name: 'user-times', styles: ['fas'] },
    { name: 'users', styles: ['fas'] },
    { name: 'users-cog', styles: ['fas'] },
    { name: 'users-slash', styles: ['fas'] },
    { name: 'usps', styles: ['fab'] },
    { name: 'ussunnah', styles: ['fab'] },
    { name: 'utensil-spoon', styles: ['fas'] },
    { name: 'utensils', styles: ['fas'] },
    { name: 'vaadin', styles: ['fab'] },
    { name: 'vector-square', styles: ['fas'] },
    { name: 'venus', styles: ['fas'] },
    { name: 'venus-double', styles: ['fas'] },
    { name: 'venus-mars', styles: ['fas'] },
    { name: 'vest', styles: ['fas'] },
    { name: 'vest-patches', styles: ['fas'] },
    { name: 'viacoin', styles: ['fab'] },
    { name: 'viadeo', styles: ['fab'] },
    { name: 'viadeo-square', styles: ['fab'] },
    { name: 'vial', styles: ['fas'] },
    { name: 'vials', styles: ['fas'] },
    { name: 'viber', styles: ['fab'] },
    { name: 'video', styles: ['fas'] },
    { name: 'video-slash', styles: ['fas'] },
    { name: 'vihara', styles: ['fas'] },
    { name: 'vimeo', styles: ['fab'] },
    { name: 'vimeo-square', styles: ['fab'] },
    { name: 'vimeo-v', styles: ['fab'] },
    { name: 'vine', styles: ['fab'] },
    { name: 'virus', styles: ['fas'] },
    { name: 'virus-slash', styles: ['fas'] },
    { name: 'viruses', styles: ['fas'] },
    { name: 'vk', styles: ['fab'] },
    { name: 'vnv', styles: ['fab'] },
    { name: 'voicemail', styles: ['fas'] },
    { name: 'volleyball-ball', styles: ['fas'] },
    { name: 'volume-down', styles: ['fas'] },
    { name: 'volume-mute', styles: ['fas'] },
    { name: 'volume-off', styles: ['fas'] },
    { name: 'volume-up', styles: ['fas'] },
    { name: 'vote-yea', styles: ['fas'] },
    { name: 'vr-cardboard', styles: ['fas'] },
    { name: 'vuejs', styles: ['fab'] },
    { name: 'walking', styles: ['fas'] },
    { name: 'wallet', styles: ['fas'] },
    { name: 'warehouse', styles: ['fas'] },
    { name: 'watchman-monitoring', styles: ['fab'] },
    { name: 'water', styles: ['fas'] },
    { name: 'wave-square', styles: ['fas'] },
    { name: 'waze', styles: ['fab'] },
    { name: 'weebly', styles: ['fab'] },
    { name: 'weibo', styles: ['fab'] },
    { name: 'weight', styles: ['fas'] },
    { name: 'weight-hanging', styles: ['fas'] },
    { name: 'weixin', styles: ['fab'] },
    { name: 'whatsapp', styles: ['fab'] },
    { name: 'whatsapp-square', styles: ['fab'] },
    { name: 'wheelchair', styles: ['fas'] },
    { name: 'whmcs', styles: ['fab'] },
    { name: 'wifi', styles: ['fas'] },
    { name: 'wikipedia-w', styles: ['fab'] },
    { name: 'wind', styles: ['fas'] },
    { name: 'window-close', styles: ['fas', 'far'] },
    { name: 'window-maximize', styles: ['fas', 'far'] },
    { name: 'window-minimize', styles: ['fas', 'far'] },
    { name: 'window-restore', styles: ['fas', 'far'] },
    { name: 'windows', styles: ['fab'] },
    { name: 'wine-bottle', styles: ['fas'] },
    { name: 'wine-glass', styles: ['fas'] },
    { name: 'wine-glass-alt', styles: ['fas'] },
    { name: 'wix', styles: ['fab'] },
    { name: 'wizards-of-the-coast', styles: ['fab'] },
    { name: 'wodu', styles: ['fab'] },
    { name: 'wolf-pack-battalion', styles: ['fab'] },
    { name: 'won-sign', styles: ['fas'] },
    { name: 'wordpress', styles: ['fab'] },
    { name: 'wordpress-simple', styles: ['fab'] },
    { name: 'wpbeginner', styles: ['fab'] },
    { name: 'wpexplorer', styles: ['fab'] },
    { name: 'wpforms', styles: ['fab'] },
    { name: 'wpressr', styles: ['fab'] },
    { name: 'wrench', styles: ['fas'] },
    { name: 'x-ray', styles: ['fas'] },
    { name: 'xbox', styles: ['fab'] },
    { name: 'xing', styles: ['fab'] },
    { name: 'xing-square', styles: ['fab'] },
    { name: 'y-combinator', styles: ['fab'] },
    { name: 'yahoo', styles: ['fab'] },
    { name: 'yammer', styles: ['fab'] },
    { name: 'yandex', styles: ['fab'] },
    { name: 'yandex-international', styles: ['fab'] },
    { name: 'yarn', styles: ['fab'] },
    { name: 'yelp', styles: ['fab'] },
    { name: 'yen-sign', styles: ['fas'] },
    { name: 'yin-yang', styles: ['fas'] },
    { name: 'yoast', styles: ['fab'] },
    { name: 'youtube', styles: ['fab'] },
    { name: 'youtube-square', styles: ['fab'] },
    { name: 'zhihu', styles: ['fab'] },
];
