#!/usr/bin/env bash
# Claude Code side of .githooks/identity-guard.sh — wired up in .claude/settings.json.
#
#   session-start  Points git at .githooks, and if git would commit as an AI tool,
#                  switches this repository to the signed-in person's identity.
#   pre-bash       Refuses a git command that would commit or push as an AI tool,
#                  carry AI attribution, or skip the git hooks, and a gh command
#                  whose GitHub text carries AI attribution. shell-facts.awk reads
#                  the command; every identity and text it finds is judged by
#                  identity-guard.sh, never here.
#   pre-github     Refuses a GitHub pull request, commit, issue, comment or review
#                  whose text (title, body, commit message) carries AI attribution.
#   post-github    After a GitHub create, reminds Claude that the GitHub connector
#                  appends its own "Generated by" footer server-side — which no
#                  pre-check can see — and that it must be edited away at once.
#
# A non-zero exit of 2 blocks the tool call and shows the reason to Claude.

set -u

project_dir="${CLAUDE_PROJECT_DIR:-$(pwd)}"
guard="$project_dir/.githooks/identity-guard.sh"
hooks_dir=$(dirname "${BASH_SOURCE[0]}")
tab=$(printf '\t')

block() {
    printf '%s\n' "$1" >&2
    exit 2
}

use_hooks() {
    [ "$(git -C "$project_dir" config core.hooksPath 2>/dev/null)" = .githooks ] || \
        git -C "$project_dir" config core.hooksPath .githooks 2>/dev/null
}

# The hook payload is JSON on stdin: print the decoded string fields named.
json_strings() {
    awk -v keys="$*" -f "$hooks_dir/json-strings.awk"
}

# The hook-skipping tokens pre-bash refuses (Architecture.md §ARC12.11 rule 4),
# a closed list matched case-insensitively against the command's text.
HOOK_SKIP_RE='--no-veri|hookspath|git_config|alias\.|include\.|includeif\.'
# The rest of the text from the word "commit", and in it a single-dash cluster
# of letters that holds an n (-n, -anm, -qn).
FROM_COMMIT_RE='(^|[^[:alnum:]_])commit([^[:alnum:]_].*|$)'
N_CLUSTER_RE='(^|[^[:alnum:]_-])-[[:alpha:]]*n[[:alpha:]]*([^[:alnum:]_-]|$)'

# hook_skipping_token <text>: prints the first hook-skipping token in the text,
# as it is written there, or nothing.
hook_skipping_token() {
    flat=$(printf '%s' "$1" | tr '\r\n' '  ')
    token=$(printf '%s\n' "$flat" | grep -Eio -e "$HOOK_SKIP_RE" | head -n 1)
    if [ -z "$token" ]; then
        token=$(printf '%s\n' "$flat" | grep -Eio -e "$FROM_COMMIT_RE" | head -n 1 | \
            grep -Eio -e "$N_CLUSTER_RE" | head -n 1 | sed -e 's/^[^-]//' -e 's/[^[:alpha:]]$//')
    fi
    printf '%s' "$token"
}

has_fact() {
    printf '%s\n' "$facts" | grep -qx "$1"
}

case "${1:-}" in
    session-start)
        use_hooks
        if ( cd "$project_dir" && bash "$guard" check-current ) >/dev/null 2>&1; then
            printf 'Git identity for commits: %s <%s>.\n' \
                "$(git -C "$project_dir" config user.name)" "$(git -C "$project_dir" config user.email)"
            exit 0
        fi

        email="${G2H_GIT_USER_EMAIL:-${CLAUDE_CODE_USER_EMAIL:-}}"
        name="${G2H_GIT_USER_NAME:-}"
        if [ -z "$name" ] && [ -n "$email" ]; then
            name=$(git -C "$project_dir" log --all -1 --format='%an' \
                --regexp-ignore-case --fixed-strings --author="<$email>" 2>/dev/null)
        fi

        if [ -n "$name" ] && [ -n "$email" ] \
            && bash "$guard" check-ident author "$name <$email>" >/dev/null 2>&1; then
            git -C "$project_dir" config user.name "$name"
            git -C "$project_dir" config user.email "$email"
            printf 'Git identity for commits set to %s <%s> for this repository. Never commit as an AI tool.\n' "$name" "$email"
            # The environment outranks the configuration: GIT_AUTHOR_* and
            # GIT_COMMITTER_* can still hold the tool's identity.
            if ! ( cd "$project_dir" && bash "$guard" check-current ) >/dev/null 2>&1; then
                printf 'WARNING: git would still commit as an AI tool, because the GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL, '
                printf 'GIT_COMMITTER_NAME or GIT_COMMITTER_EMAIL environment variables override the configuration. '
                printf 'Every commit will be refused until they are unset or set to the person.\n'
            fi
            exit 0
        fi

        printf 'WARNING: git would commit as an AI tool and the signed-in person could not be resolved. '
        printf 'Every commit will be refused. Ask the user for the name and email to commit under, then run: '
        printf 'git config user.name "<name>" && git config user.email "<email>". '
        printf 'In a cloud environment, set G2H_GIT_USER_NAME and G2H_GIT_USER_EMAIL in the environment settings.\n'
        exit 0
        ;;

    pre-bash)
        use_hooks
        payload=$(cat)
        command=$(printf '%s' "$payload" | json_strings command)
        [ -n "$command" ] || exit 0
        token=$(hook_skipping_token "$command")
        if [ -n "$token" ]; then
            block "Refused: \"$token\" in this command can skip or redirect this repository's git hooks, which keep AI identities and attribution out of the history. The check matches text, so a command that only mentions it is refused too: rephrase it."
        fi
        facts=$(printf '%s\n' "$command" | awk -f "$hooks_dir/shell-facts.awk")
        [ -n "$facts" ] || exit 0

        while IFS="$tab" read -r kind label ident; do
            case "$kind" in
                SKIP)
                    block "Refused: this repository does not allow skipping or redirecting its git hooks ($label). They keep AI identities and attribution out of the history."
                    ;;
                IDENT)
                    if ! reason=$(bash "$guard" check-ident "$label" "$ident" 2>&1); then
                        block "Refused: $reason"
                    fi
                    ;;
                FILE)
                    cwd=$(printf '%s' "$payload" | json_strings cwd)
                    if ! reason=$( cd "${cwd:-$project_dir}" 2>/dev/null; [ ! -f "$label" ] || \
                        GUARD_LABEL="$label" bash "$guard" check-text <"$label" 2>&1 ); then
                        block "Refused: $reason"
                    fi
                    ;;
            esac
        done <<<"$facts"
        if has_fact HISTORY || has_fact GH; then
            if ! reason=$(printf '%s\n' "$command" | GUARD_LABEL='this command' bash "$guard" check-text 2>&1); then
                block "Refused: $reason"
            fi
        fi
        if has_fact COMMIT; then
            if ! reason=$( cd "$project_dir" && bash "$guard" check-current 2>&1 ); then
                block "Refused: $reason"
            fi
        fi
        exit 0
        ;;

    pre-github)
        # Only the text GitHub shows as written by someone: never a file's contents.
        text=$(json_strings title body commit_title commit_message message)
        if ! reason=$(printf '%s\n' "$text" | GUARD_LABEL='this GitHub pull request, commit, issue or comment' bash "$guard" check-text 2>&1); then
            block "Refused: $reason"
        fi
        exit 0
        ;;
    post-github)
        printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"The GitHub connector appends an AI attribution footer (\"Generated by [Claude Code]\") to what it creates, after this repository'"'"'s pre-check has run. This repository forbids AI attribution. Re-read what was just created and, if the footer is there, edit it away now: update_issue_comment for a comment, issue_write update for an issue, update_pull_request for a pull request, discussion_comment_write update for a discussion comment."}}'
        exit 0
        ;;
esac

exit 0
