#!/bin/bash
# ────────────────────────────────────────────────────────────────────────────────
# Generates a deployable SQL migration script that applies correctly under ANY
# client's SET defaults.
#
# `dotnet ef migrations script --idempotent` emits no SET statements at all. That
# is fine when EF applies the migrations itself — SqlClient connects with
# QUOTED_IDENTIFIER ON — but it is not fine for the script, because several
# migrations create filtered indexes and indexes on computed columns, and SQL
# Server refuses those unless a specific set of options is ON.
#
# sqlcmd defaults QUOTED_IDENTIFIER OFF. Applying the raw script with it therefore
# fails on the FIRST migration:
#
#   Msg 1934 — CREATE INDEX failed because the following SET options have
#              incorrect settings: 'QUOTED_IDENTIFIER'.
#
# `sqlcmd -I` fixes it, but that puts the correctness of a deployment in the hands
# of whoever remembers a flag. This prepends the required options to the artifact
# instead, so the file is correct on its own however it is applied.
#
# Usage:
#   Tools/new-database-script.sh [output-path]
#
# Default output: ./Glory2Him.Core.Database.sql
#
# Apply with:
#   sqlcmd -S <server> -d <database> -i <output-path> -b
#
# The script is idempotent: applying it to an up-to-date database is a no-op, and
# applying it to an empty one builds the whole schema.
# ────────────────────────────────────────────────────────────────────────────────

set -euo pipefail

OUTPUT_PATH="${1:-Glory2Him.Core.Database.sql}"
PROJECT="Glory2Him.Core"
TEMP_PATH="${OUTPUT_PATH}.tmp"

if [ ! -d "$PROJECT" ]; then
    echo "error: run this from the repository root — '$PROJECT' not found here." >&2
    exit 1
fi

echo "Generating idempotent migration script from $PROJECT ..."
dotnet ef migrations script --idempotent --project "$PROJECT" --output "$TEMP_PATH"

echo "Prepending required SET options ..."

# These are the options SQL Server requires for filtered indexes and for indexes
# on computed columns. NUMERIC_ROUNDABORT is the one that must be OFF.
# Documented at:
#   https://learn.microsoft.com/sql/relational-databases/indexes/create-filtered-indexes
{
    printf '%s\n' \
        '-- ────────────────────────────────────────────────────────────────────' \
        '-- Required SET options.' \
        '--' \
        '-- This schema uses filtered indexes and indexes on computed columns.' \
        '-- SQL Server refuses to create or modify those unless these options are' \
        '-- set as below. sqlcmd defaults QUOTED_IDENTIFIER to OFF, so without this' \
        '-- header the very first CREATE INDEX fails with Msg 1934.' \
        '--' \
        '-- Generated by Tools/new-database-script.sh — do not hand-edit.' \
        '-- ────────────────────────────────────────────────────────────────────' \
        'SET ANSI_NULLS ON;' \
        'SET ANSI_PADDING ON;' \
        'SET ANSI_WARNINGS ON;' \
        'SET ARITHABORT ON;' \
        'SET CONCAT_NULL_YIELDS_NULL ON;' \
        'SET QUOTED_IDENTIFIER ON;' \
        'SET NUMERIC_ROUNDABORT OFF;' \
        'GO' \
        ''
    # strip the UTF-8 BOM EF writes, so it cannot land mid-file after the header
    sed '1s/^\xEF\xBB\xBF//' "$TEMP_PATH"
} > "$OUTPUT_PATH"

rm -f "$TEMP_PATH"

echo "Wrote $OUTPUT_PATH ($(wc -c < "$OUTPUT_PATH") bytes)."
echo
echo "Apply with:"
echo "  sqlcmd -S <server> -d <database> -i $OUTPUT_PATH -b"
